# docker-compose.yml
version: '3'
services:
    flask:
        image: webapp-flask
        build:
            context: ./Flask
        volumes:
            - "../:/app"
        depends_on: 
            - mongodb
        networks:    
            - backend        
        environment: 
            - NETFLIX_API_URL=${NETFLIX_API_URL}
            - NETFLIX_API_KEY=${NETFLIX_API_KEY}
            - FILE_OFFSET_LOCATION=${FILE_OFFSET_LOCATION}
            - DB_USER=${DB_USERNAME}
            - DB_PASS=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - FB_APP_ID=${FACEBOOK_APP_ID}
            - FB_SECRET_KEY=${FACEBOOK_SECRET_KEY}
            - OAUTHLIB_INSECURE_TRANSPORT=${INSECURE_TRANSPORT}
            - MAIL_SERVER=${MAIL_SERVER}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_USE_TLS=${MAIL_USE_TLS}
            - MAIL_USE_SSL=${MAIL_USE_SSL}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_ADMIN=${MAIL_ADMIN}
    nginx:
        image: webapp-nginx
        build:
            context: ./Nginx
        ports:
            - 5000:80
        depends_on:
            - flask
        networks:
            - frontend    
            - backend    
    
    mongodb:
        image: mongo:latest
        container_name: "server_mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            #- MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            #- MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}      
            - MONGO_INITDB_DATABASE=${DB_NAME}
        volumes:
            - databases:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet
        networks:    
            - backend    


volumes:
  databases:

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"